version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      - MONGO_URI=$MONGO_URI
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0.4
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    ports:
      - "27017:27017"